### ISSUE TITLE
General error: property queryString is read only

### ISSUE THREAD

**Issue by sameg14** [myclabs/DeepCopy#25] opened 2015-10-06 16:13 UTC
Since we upgraded to the latest version, 1.4.0 we are getting this error when running tests in codeception.  

- Removing myclabs/deep-copy (1.3.1)
- Installing myclabs/deep-copy (1.4.0)
```bash
PDOException: SQLSTATE[HY000]: General error: property queryString is read only

#1  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:160
#2  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:123
#3  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:75
#4  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:160
#5  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:123
#6  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:75
#7  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:86
#8  DeepCopy\DeepCopy->DeepCopy\{closure}
#9  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:89
#10 /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:68
```

**Comment by mnapoli** [comment] 2015-10-06 17:06
Hi, thank you for the report. This might be a regression due to #23 (1.4.0 only contained this), the question is: is this a bug in this package, or your code?

If there's a MySQL error, it might be great to investigate how/why DeepCopy is inserting anything in database? Where comes the `queryString` from? Is this a private parent property that gets copied at the wrong place?

**Comment by sameg14** [comment] 2015-10-06 17:19
I have no idea where queryString comes from. We rolled back the package version to `1.3.1` and everything works, so its not the code. I would add an if() check prior to recursing.

**Comment by mnapoli** [comment] 2015-10-06 17:22
I have pushed more tests, I can't reproduce the problem.

> and everything works, so its not the code

I meant it could be your code doing something wrong, that wasn't causing an issue before but now it's visible. Please search for a **private** `$queryString` property in your code base. Maybe it's a private property in a root class of your objects that your a trying to clone?

**Comment by sameg14** [comment] 2015-10-07 21:16
```bash
samir@wfm:/htdocs/api-main-php (SAGE-1966-implement-encryption)$ grep -inr 'private $queryString' .
./vendor/symfony/symfony/src/Symfony/Component/Routing/RequestContext.php:35:    private $queryString;
```
Also have no idea why `RequestContext` is being used.

This is the only thing that comes up. Basically the error gets thrown in a Codeception test. This is what the test looks like. 
```php
    public function testStateSearchShouldThrowExceptionIfStateIsEmpty()
    {
        $this->specify('InvalidDataException if state is empty', function () {

            $this->storeService->setSearchType('state');
            $this->storeService->setState(null);
            $this->storeService->generateSearchQuery();

        }, ['throws' => 'Wfm\CoreBundle\Exception\InvalidSearchParameterException']);
    }
```

This is the error from jenkins
```bash
1) [1mtests\unit\Wfm\ApiBundle\Service\StoreServiceTest::testStateSearchShouldThrowExceptionIfStateIsEmpty | InvalidDataException if state is empty[22m
PDOException: SQLSTATE[HY000]: General error: property queryString is read only

#1  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:160
#2  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:123
#3  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:75
#4  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:160
#5  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:123
#6  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:75
#7  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:86
#8  DeepCopy\DeepCopy->DeepCopy\{closure}
#9  /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:89
#10 /var/jenkins/workspace/Integration-API-MAIN-PHP-Testing/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:68
```

**Comment by mnapoli** [comment] 2015-10-08 11:54
I'm sorry I cannot help you much more without knowing what your code does. Why is there a database exception? What is stored in the database when your service generates a search query?

The error is:

> PDOException: SQLSTATE[HY000]: General error: property queryString is read only

So it means something is being queried against the database, and that something seem to contain the `RequestContext` object (and PDO can't map that to the DB apparently).

Unless you can provide more information to identify a bug in this library I have to close it. We can reopen this issue if we identify a bug but at this point it seems very likely it's something in your code (private property in a parent class gets cloned and you didn't expect it, and it crashes when inserting the object in DB).

**Closed by mnapoli** 2015-10-08 11:54 UTC

**Comment by sameg14** [comment] 2015-10-13 23:31
I guess that's a fair point. Let me spend some more time on this and try and figure out why that particular class is being used in this test. There isn't really a reference to it so maybe its coming out of the service container in some way. I'll open another issue if I figure it out. Thanks for taking the time to look into this man. Good job with the package!

**Comment by frankenpfalzer** [comment] 2016-06-05 21:31
Actually I got the same problem here with version 1.5.1.

I suppose that `PDOStatements` are the problem. The properties in my class are a mingle-mangle of `int`, `string`, a `PDO` instance and some `PDOStatements`.

Here is my stacktrace:

```
#0 ./myApp/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(182): ReflectionProperty->setValue(Object(PDOStatement), 'SELECT * FROM t...')
#1 ./myApp/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(145): DeepCopy\DeepCopy->copyObjectProperty(Object(PDOStatement), Object(ReflectionProperty))
#2 ./myApp/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(97): DeepCopy\DeepCopy->copyObject(Object(PDOStatement))
#3 ./myApp/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(182): DeepCopy\DeepCopy->recursiveCopy(Object(PDOStatement))
#4 ./myApp/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(145): DeepCopy\DeepCopy->copyObjectProperty(Object(DOTeam), Object(ReflectionProperty))
#5 ./myApp/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(97): DeepCopy\DeepCopy->copyObject(Object(DOTeam))
#6 ./myApp/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(57): DeepCopy\DeepCopy->recursiveCopy(Object(DOTeam))
#7 ./myApp/src/teams/SportAdminTeamsModel.inc.php(142): DeepCopy\DeepCopy->copy(Object(DOTeam))
#8 ./myApp/src/teams/SportAdminTeamsController.inc.php(55): SportAdminTeamsModel->loadSelectedTeam('61')
#9 ./myApp/src/SportAdminController.inc.php(49): SportAdminTeamsController->__construct(Object(DOMember), Object(PDO), 'teams', 'edit', Array)
#10 ./myApp/index.php(92): SportAdminController->__construct(true, Object(DOMember), Object(PDO), 'teams', 'edit', Array)
#11 {main}
```

**Comment by mnapoli** [comment] 2016-06-06 06:24
@frankenpfalzer I suppose you don't want to clone PDO statements, you can exclude them (exclude the property that contains them).

**Comment by frankenpfalzer** [comment] 2016-06-08 20:34
@mnapoli Thank you for the hint. I added
```
$deepCopy->addFilter(new KeepFilter(), new PropertyMatcher("DOTeam", "pdo"));
$deepCopy->addFilter(new KeepFilter(), new PropertyMatcher("DOTeam", "preparedLoadStatement"));
...
```
to my model class. The copy process works now without a exception, but im a little confused about the behaviour of the copied porperties.
Here is some example code:
```
$this->team = new DOTeam($this->pdo);
$this->team->load($id);
$this->team->getId(); // 42
$deepCopy = new DeepCopy();
$deepCopy->addFilter(new KeepFilter(), new PropertyMatcher("DOTeam", "pdo"));
$deepCopy->addFilter(new KeepFilter(), new PropertyMatcher("DOTeam", "preparedLoadStatement"));
$team2 = $deepCopy->copy($this->team);
$team2->setId("355");
$this->team->getId(); // 355
```
I don't get it. Why does not contain `$this->team` 42? I thought the normal `clone` is using the same references und `DeepCopy` generates new references with the same values.

Maybe it's too late and I need some sleep but i fear that will not solve my problem ;-)

**Comment by mnapoli** [comment] 2016-06-08 21:14
@frankenpfalzer I don't know how the internals of your objects work but maybe something is preventing the clone to execute properly (especially if there's something database-related)
